--- Entity accessors generated by SimpleNet.
---
--- `Photon.SNet:Map` hangs a `Set`/`Get` pair off the `Entity` metatable for
--- every variable it registers, at load time. Nothing declares them in source,
--- so neither the editor nor the docs site can see them — this file declares
--- them instead, mirroring what `sh_simplenet.lua` registers at the bottom.
---
--- Definitions only: `--- @meta` marks the whole file as declarations rather
--- than executable code, and nothing includes it — `lua/autorun/photon/meta/`
--- is not on any load path, and its `.glualint.json` turns off the
--- unused-variable warning every empty declaration in here would otherwise
--- raise. Keep it in step with the `Photon.SNet:Map` calls in
--- [sh_simplenet.lua](https://github.com/photonle/Photon/blob/development/lua/autorun/photon/shared/sh_simplenet.lua) —
--- a name that is registered but not declared here still works at runtime, it
--- is only invisible to tooling.
---
--- Every getter takes the value to fall back on when the client has not been
--- told the real one yet, and every setter is serverside: a client that writes
--- one changes only its own copy, until the next broadcast overwrites it.
--- @copyright Photon Team
--- @author Photon Team
--- @namespace Entity
--- @state shared

--- @meta

--- @class Entity
local ENTITY = {}

--- Set whether the vehicle is a Photon vehicle, i.e. whether `Photon:SetupCar`
--- has run on it. Set once during setup and never cleared.
--- @param value boolean Whether the vehicle has Photon.
--- @state server
--- @section Vehicle State
function ENTITY:SetPhotonNet_HasPhoton(value) end

--- Whether the vehicle is a Photon vehicle. Prefer `Entity:Photon`, which is
--- the supported way to ask and also covers the non-vehicle case.
--- @param default boolean? Value to return if none has been networked yet.
--- @return boolean hasPhoton Whether the vehicle has Photon.
--- @state shared
function ENTITY:GetPhotonNet_HasPhoton(default) end

--- Set the vehicle's turn-signal state, as one of the `CAR_BLINKER_*` constants.
--- @param value integer New signal value.
--- @state server
function ENTITY:SetPhotonNet_CurrentSignal(value) end

--- The vehicle's turn-signal state, as one of the `CAR_BLINKER_*` constants.
--- @param default integer? Value to return if none has been networked yet.
--- @return integer signal Current signal value.
--- @state shared
function ENTITY:GetPhotonNet_CurrentSignal(default) end

--- Set the vehicle's blinker state.
--- @param value integer New blinker value.
--- @ambig Registered, but nothing in the engine reads or writes it — the live
--- signal state is `CurrentSignal`.
--- @state server
function ENTITY:SetPhotonNet_Blinker(value) end

--- The vehicle's blinker state.
--- @param default integer? Value to return if none has been networked yet.
--- @return integer blinker Current blinker value.
--- @ambig Registered, but nothing in the engine reads or writes it — the live
--- signal state is `CurrentSignal`.
--- @state shared
function ENTITY:GetPhotonNet_Blinker(default) end

--- Set whether the vehicle's headlights are on.
--- @param value boolean Whether the headlights are on.
--- @ambig Registered, but nothing in the engine reads or writes it.
--- @state server
function ENTITY:SetPhotonNet_Headlights(value) end

--- Whether the vehicle's headlights are on.
--- @param default boolean? Value to return if none has been networked yet.
--- @return boolean on Whether the headlights are on.
--- @ambig Registered, but nothing in the engine reads or writes it.
--- @state shared
function ENTITY:GetPhotonNet_Headlights(default) end

--- Set whether the vehicle is braking.
--- @param value boolean Whether the vehicle is braking.
--- @state server
function ENTITY:SetPhotonNet_Braking(value) end

--- Whether the vehicle is braking.
--- @param default boolean? Value to return if none has been networked yet.
--- @return boolean braking Whether the vehicle is braking.
--- @state shared
function ENTITY:GetPhotonNet_Braking(default) end

--- Set whether the vehicle is reversing.
--- @param value boolean Whether the vehicle is reversing.
--- @state server
function ENTITY:SetPhotonNet_Reversing(value) end

--- Whether the vehicle is reversing.
--- @param default boolean? Value to return if none has been networked yet.
--- @return boolean reversing Whether the vehicle is reversing.
--- @state shared
function ENTITY:GetPhotonNet_Reversing(default) end

--- Set whether the vehicle's engine is running.
--- @param value boolean Whether the engine is running.
--- @state server
function ENTITY:SetPhotonNet_Running(value) end

--- Whether the vehicle's engine is running.
--- @param default boolean? Value to return if none has been networked yet.
--- @return boolean running Whether the engine is running.
--- @state shared
function ENTITY:GetPhotonNet_Running(default) end

--- Set whether the vehicle's emergency lighting stays on with the engine off.
--- @param value boolean Whether lighting stays on.
--- @state server
--- @section Emergency Lighting
function ENTITY:SetPhotonNet_LEStayOn(value) end

--- Whether the vehicle's emergency lighting stays on with the engine off.
--- @param default boolean? Value to return if none has been networked yet.
--- @return boolean stayOn Whether lighting stays on.
--- @state shared
function ENTITY:GetPhotonNet_LEStayOn(default) end

--- Set whether emergency lighting is enabled on the vehicle. Read through
--- `Entity:ELS_Enabled`; whether the vehicle has Photon at all is `HasPhoton`.
--- @param value boolean Whether emergency lighting is enabled.
--- @state server
function ENTITY:SetPhotonNet_Enabled(value) end

--- Whether emergency lighting is enabled on the vehicle.
--- @param default boolean? Value to return if none has been networked yet.
--- @return boolean enabled Whether emergency lighting is enabled.
--- @state shared
function ENTITY:GetPhotonNet_Enabled(default) end

--- Set whether the vehicle's emergency lights are on.
--- @param value boolean Whether the lights are on.
--- @state server
function ENTITY:SetPhotonNet_LightOn(value) end

--- Whether the vehicle's emergency lights are on.
--- @param default boolean? Value to return if none has been networked yet.
--- @return boolean on Whether the lights are on.
--- @state shared
function ENTITY:GetPhotonNet_LightOn(default) end

--- Set the vehicle's active lighting stage.
--- @param value integer Lighting option index, 1-16.
--- @state server
function ENTITY:SetPhotonNet_LightOption(value) end

--- The vehicle's active lighting stage.
--- @param default integer? Value to return if none has been networked yet.
--- @return integer option Lighting option index.
--- @state shared
function ENTITY:GetPhotonNet_LightOption(default) end

--- Set the vehicle's active lighting preset.
--- @param value integer Preset index; 0 for none.
--- @state server
function ENTITY:SetPhotonNet_Preset(value) end

--- The vehicle's active lighting preset.
--- @param default integer? Value to return if none has been networked yet.
--- @return integer preset Preset index; 0 for none.
--- @state shared
function ENTITY:GetPhotonNet_Preset(default) end

--- Set whether the vehicle is blacked out.
--- @param value boolean Whether the vehicle is blacked out.
--- @state server
function ENTITY:SetPhotonNet_Blackout(value) end

--- Whether the vehicle is blacked out, suppressing its running lights.
--- @param default boolean? Value to return if none has been networked yet.
--- @return boolean blackout Whether the vehicle is blacked out.
--- @state shared
function ENTITY:GetPhotonNet_Blackout(default) end

--- Set whether the vehicle's siren is on.
--- @param value boolean Whether the siren is on.
--- @state server
--- @section Siren
function ENTITY:SetPhotonNet_SirenOn(value) end

--- Whether the vehicle's siren is on.
--- @param default boolean? Value to return if none has been networked yet.
--- @return boolean on Whether the siren is on.
--- @state shared
function ENTITY:GetPhotonNet_SirenOn(default) end

--- Set the vehicle's primary siren set.
--- @param value integer Siren set index, 1-1024.
--- @state server
function ENTITY:SetPhotonNet_SirenSet(value) end

--- The vehicle's primary siren set.
--- @param default integer? Value to return if none has been networked yet.
--- @return integer set Siren set index.
--- @state shared
function ENTITY:GetPhotonNet_SirenSet(default) end

--- Set the vehicle's active siren tone.
--- @param value integer Siren option index, 1-16.
--- @state server
function ENTITY:SetPhotonNet_SirenOption(value) end

--- The vehicle's active siren tone.
--- @param default integer? Value to return if none has been networked yet.
--- @return integer option Siren option index.
--- @state shared
function ENTITY:GetPhotonNet_SirenOption(default) end

--- Set the vehicle's auxiliary siren set.
--- @param value integer Siren set index, 1-1024.
--- @state server
function ENTITY:SetPhotonNet_AuxSirenSet(value) end

--- The vehicle's auxiliary siren set.
--- @param default integer? Value to return if none has been networked yet.
--- @return integer set Siren set index.
--- @state shared
function ENTITY:GetPhotonNet_AuxSirenSet(default) end

--- Set the sound playing on the vehicle's primary siren channel. Setting it
--- starts playback; clearing it to an empty string stops the channel.
--- @param value string Sound file or script to play, or `""` to stop.
--- @state server
function ENTITY:SetPhotonNet_SirenSound(value) end

--- The sound playing on the vehicle's primary siren channel.
--- @param default string? Value to return if none has been networked yet.
--- @return string sound Sound file or script, or `""` when the channel is silent.
--- @state shared
function ENTITY:GetPhotonNet_SirenSound(default) end

--- Set the sound level of the vehicle's primary siren, taken from the siren
--- set's `Volume` field.
--- @param value number Source sound level (SNDLVL), not a 0-1 scale.
--- @state server
function ENTITY:SetPhotonNet_SirenVolume(value) end

--- The sound level of the vehicle's primary siren.
--- @param default number? Value to return if none has been networked yet.
--- @return number level Source sound level (SNDLVL), not a 0-1 scale.
--- @state shared
function ENTITY:GetPhotonNet_SirenVolume(default) end

--- Set the sound playing on the vehicle's secondary siren channel, layered
--- over the primary siren when the vehicle has an auxiliary siren set.
--- @param value string Sound file or script to play, or `""` to stop.
--- @state server
function ENTITY:SetPhotonNet_Siren2Sound(value) end

--- The sound playing on the vehicle's secondary siren channel.
--- @param default string? Value to return if none has been networked yet.
--- @return string sound Sound file or script, or `""` when the channel is silent.
--- @state shared
function ENTITY:GetPhotonNet_Siren2Sound(default) end

--- Set the sound level of the vehicle's secondary siren. Taken from the
--- primary siren set's `Volume` field, even though the tone itself comes from
--- the auxiliary set.
--- @param value number Source sound level (SNDLVL), not a 0-1 scale.
--- @state server
function ENTITY:SetPhotonNet_Siren2Volume(value) end

--- The sound level of the vehicle's secondary siren.
--- @param default number? Value to return if none has been networked yet.
--- @return number level Source sound level (SNDLVL), not a 0-1 scale.
--- @state shared
function ENTITY:GetPhotonNet_Siren2Volume(default) end

--- Set the sound playing on the vehicle's manual siren channel. Starting one
--- ducks the primary siren rather than stopping it, so clearing this resumes
--- the primary siren instead of replaying it from the start.
--- @param value string Sound file or script to play, or `""` to stop.
--- @state server
function ENTITY:SetPhotonNet_ManualSound(value) end

--- The sound playing on the vehicle's manual siren channel.
--- @param default string? Value to return if none has been networked yet.
--- @return string sound Sound file or script, or `""` when the channel is silent.
--- @state shared
function ENTITY:GetPhotonNet_ManualSound(default) end

--- Set the sound level of the vehicle's manual siren, taken from the siren
--- set's `Volume` field.
--- @param value number Source sound level (SNDLVL), not a 0-1 scale.
--- @state server
function ENTITY:SetPhotonNet_ManualVolume(value) end

--- The sound level of the vehicle's manual siren.
--- @param default number? Value to return if none has been networked yet.
--- @return number level Source sound level (SNDLVL), not a 0-1 scale.
--- @state shared
function ENTITY:GetPhotonNet_ManualVolume(default) end

--- Set the sound playing on the vehicle's horn channel. Setting it starts
--- playback; clearing it to an empty string stops the channel.
--- @param value string Sound file or script to play, or `""` to stop.
--- @state server
function ENTITY:SetPhotonNet_HornSound(value) end

--- The sound playing on the vehicle's horn channel.
--- @param default string? Value to return if none has been networked yet.
--- @return string sound Sound file or script, or `""` when the channel is silent.
--- @state shared
function ENTITY:GetPhotonNet_HornSound(default) end

--- Set the sound level of the vehicle's horn, taken from the siren set's
--- `Volume` field.
--- @param value number Source sound level (SNDLVL), not a 0-1 scale.
--- @state server
function ENTITY:SetPhotonNet_HornVolume(value) end

--- The sound level of the vehicle's horn.
--- @param default number? Value to return if none has been networked yet.
--- @return number level Source sound level (SNDLVL), not a 0-1 scale.
--- @state shared
function ENTITY:GetPhotonNet_HornVolume(default) end

--- Set whether the vehicle's traffic advisor is on.
--- @param value boolean Whether the traffic advisor is on.
--- @state server
--- @section Traffic Advisor
function ENTITY:SetPhotonNet_TrafficOn(value) end

--- Whether the vehicle's traffic advisor is on.
--- @param default boolean? Value to return if none has been networked yet.
--- @return boolean on Whether the traffic advisor is on.
--- @state shared
function ENTITY:GetPhotonNet_TrafficOn(default) end

--- Set the vehicle's traffic advisor pattern.
--- @param value integer Traffic option index, 1-16.
--- @state server
function ENTITY:SetPhotonNet_TrafficOption(value) end

--- The vehicle's traffic advisor pattern.
--- @param default integer? Value to return if none has been networked yet.
--- @return integer option Traffic option index.
--- @state shared
function ENTITY:GetPhotonNet_TrafficOption(default) end

--- Set whether the vehicle's scene illumination is on.
--- @param value boolean Whether illumination is on.
--- @state server
--- @section Illumination
function ENTITY:SetPhotonNet_IlluminationOn(value) end

--- Whether the vehicle's scene illumination is on.
--- @param default boolean? Value to return if none has been networked yet.
--- @return boolean on Whether illumination is on.
--- @state shared
function ENTITY:GetPhotonNet_IlluminationOn(default) end

--- Set the vehicle's active illumination stage.
--- @param value integer Illumination option index, 1-16.
--- @state server
function ENTITY:SetPhotonNet_IlluminationOption(value) end

--- The vehicle's active illumination stage.
--- @param default integer? Value to return if none has been networked yet.
--- @return integer option Illumination option index.
--- @state shared
function ENTITY:GetPhotonNet_IlluminationOption(default) end

--- Set the registered name of the Photon vehicle this entity is running.
--- @param value string Vehicle index, as registered in `Photon.Vehicles`.
--- @state server
--- @section Identity
function ENTITY:SetPhotonNet_VehicleIndex(value) end

--- The registered name of the Photon vehicle this entity is running.
--- Everything else about the vehicle is looked up from this, so a client that
--- has not received it yet cannot render the vehicle at all.
--- @param default string? Value to return if none has been networked yet.
--- @return string index Vehicle index.
--- @state shared
function ENTITY:GetPhotonNet_VehicleIndex(default) end

--- Set the vehicle's displayed unit number.
--- @param value string Unit number.
--- @state server
function ENTITY:SetPhotonNet_UnitNumber(value) end

--- The vehicle's displayed unit number.
--- @param default string? Value to return if none has been networked yet.
--- @return string number Unit number.
--- @state shared
function ENTITY:GetPhotonNet_UnitNumber(default) end

--- Set the vehicle's selected livery.
--- @param value string Livery ID.
--- @state server
function ENTITY:SetPhotonNet_LiveryID(value) end

--- The vehicle's selected livery.
--- @param default string? Value to return if none has been networked yet.
--- @return string id Livery ID.
--- @state shared
function ENTITY:GetPhotonNet_LiveryID(default) end

--- Set the vehicle's auto-livery selection, as a `.`-joined path of indices.
--- @param value string Selection string.
--- @state server
function ENTITY:SetPhotonNet_SelectionString(value) end

--- The vehicle's auto-livery selection, as a `.`-joined path of indices.
--- @param default string? Value to return if none has been networked yet.
--- @return string selection Selection string.
--- @state shared
function ENTITY:GetPhotonNet_SelectionString(default) end
