CreateConVar("photon_emv_changesirens", "1", FCVAR_ARCHIVE, "Whether players are permitted to change their siren model or not")
CreateConVar("photon_emv_changepresets", "1", FCVAR_ARCHIVE, "Whether players are permitted to change emergency lighting presets")
CreateConVar("photon_emv_unitnumbers", "1", FCVAR_ARCHIVE, "Whether players are permitted to use custom unit numbers")
CreateConVar("photon_emv_allowradar", "1", FCVAR_ARCHIVE, "Whether vehicle speed radar is enabled or not")
-- CreateConVar("photon_emv_useillum", "1", FCVAR_ARCHIVE, "Whether emergency vehicle illumination should render light")