name: GLuaTest Runner

on:
  pull_request:
  push:
    branches:
      - development

jobs:
  run-tests:
    uses: CFC-Servers/GLuaTest/.github/workflows/run_tests.yml@main
    with:
      gamemode: sandbox
      map: gm_construct
